I was thinking of neural networks as focusing a cone made up of hyperplanes in parameter space. However, after staring at a 2D example for a while, I'm thinking it might be more like a 'snake' moving through parameter space. In my mind, the parameter search kind of looks like the alien-controlled column of water in *the Abyss*. I want to see a simple example of this to see if I'm right.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x1 = np.array([-5,0,1])
x2 = np.array([1,2,0])
x3 = np.array([0,1,-10])

mu, sigma = 0, 1/np.sqrt(3)

W = np.random.normal(mu, sigma, 18)

In [7]:
z1 = np.array([-5*W[0] + W[1], 2*W[1] + W[2], W[0] - 10*W[2]])
z2 = np.array([-5*W[3] + W[4], 2*W[4] + W[5], W[3] - 10*W[5]])
z3 = np.array([-5*W[6] + W[7], 2*W[7] + W[8], W[6] - 10*W[8]])

In [12]:
# Plotting the first nine planes
normal1 = x1
normal2 = x2
normal3 = x3

# These go with normal1
point11 = z1[0]
point12 = z2[0]
point13 = z3[0]

# These go with normal2
point21 = z1[1]
point22 = z2[1]
point23 = z3[1]

# These go with normal3
point31 = z1[2]
point32 = z2[2]
point33 = z3[2]

In [18]:
%matplotlib qt

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# a plane is a*x+b*y+c*z+d=0
# [a,b,c] is the normal. Thus, we have to calculate
# d and we're set

# create x,y
xx, yy = np.meshgrid(range(10), range(10))

# calculate corresponding z
z11 = (-normal1[0] * xx - normal1[1] * yy + point11) * 1. /normal1[2]
z12 = (-normal1[0] * xx - normal1[1] * yy + point12) * 1. /normal1[2]
z13 = (-normal1[0] * xx - normal1[1] * yy + point13) * 1. /normal1[2]

z21 = (-normal2[0] * xx - normal2[1] * yy + point21) * 1. /normal2[2]
z22 = (-normal2[0] * xx - normal2[1] * yy + point22) * 1. /normal2[2]
z23 = (-normal2[0] * xx - normal2[1] * yy + point23) * 1. /normal2[2]

z31 = (-normal3[0] * xx - normal3[1] * yy + point31) * 1. /normal3[2]
z32 = (-normal3[0] * xx - normal3[1] * yy + point32) * 1. /normal3[2]
z33 = (-normal3[0] * xx - normal3[1] * yy + point33) * 1. /normal3[2]


# plot the surface
plt3d = plt.figure().gca(projection='3d')

# First three planes
plt3d.plot_surface(xx, yy, z11)
plt3d.plot_surface(xx, yy, z12)
plt3d.plot_surface(xx, yy, z13)

# Next three planes
plt3d.plot_surface(xx, yy, z21)
plt3d.plot_surface(xx, yy, z22)
plt3d.plot_surface(xx, yy, z23)

# Final three planes
plt3d.plot_surface(xx, yy, z31)
plt3d.plot_surface(xx, yy, z32)
plt3d.plot_surface(xx, yy, z33)

plt.show()

C:\Users\Matt\anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide
C:\Users\Matt\anaconda3\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: divide by zero encountered in true_divide
C:\Users\Matt\anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: divide by zero encountered in true_divide


In [19]:
point11, point12, point13

(1.1559379191006471, -1.9073049166768055, -1.6885633030435376)

In [20]:
point21, point22, point23

(1.188702993164267, -0.5464574660598779, -0.4780620506680915)

In [21]:
point31, point32, point33

(-8.628764018573367, 2.163970355038466, -1.75583967707902)

In [22]:
W[9]*point11 + W[10]*point21, W[12]*point11 + W[13]*point21, W[15]*point11 + W[16]*point21

(0.9228058248132451, 0.2582515357277924, -0.1054807747816886)

In [23]:
W[11]*point32, W[14]*point32, W[17]*point32

(0.5399482169223709, 0.5864778845552039, -1.1476529019234167)

In [24]:
y1 = np.array([W[9]*point11 + W[10]*point21, W[11]*point32, 0])
y2 = np.array([W[12]*point11 + W[13]*point21, W[14]*point32, 0])
y3 = np.array([W[15]*point11 + W[16]*point21, W[17]*point32, 0])

In [25]:
# Plotting the second nine planes
normal1 = y1
normal2 = y2
normal3 = y3

# These go with normal1
point11 = y1[0]
point12 = y2[0]
point13 = y3[0]

# These go with normal2
point21 = y1[1]
point22 = y2[1]
point23 = y3[1]

# These go with normal3
point31 = y1[2]
point32 = y2[2]
point33 = y3[2]

It's getting hard to plot this in 3D, so let's try it in 2D and see what happens.

In [8]:
import numpy as np

x1 = np.array([1,0])
x2 = np.array([0,1])

mu, sigma = 0, 1/np.sqrt(2)

W1 = np.random.normal(mu, sigma, 4)

# First trailing number is the layer, second number is the unit
# Note: the order I use the W1 values doesn't matter
z11 = W1[0]*x1 + W1[1]*x2
z12 = W1[2]*x1 + W1[3]*x2

In [9]:
z11, z12

(array([-0.12236906,  0.06756541]), array([-0.48885834, -0.82781495]))

In [10]:
a11 = np.array([z11[0], 0])
a12 = np.array([0, 0])

W2 = np.random.normal(mu, sigma, 4)

z21 = W2[0]*a11 + W2[1]*a12
z22 = W2[2]*a11 + W2[3]*a12

z21, z22

(array([-0.05833829,  0.        ]), array([ 0.03259977, -0.        ]))

In [11]:
a21 = np.array([0, 0])
a22 = np.array([z21[0], 0])

W3 = np.random.normal(mu, sigma, 4)

z31 = W3[0]*a21 + W3[1]*a22
z32 = W3[2]*a21 + W3[3]*a22

z31, z32

(array([-0.02721093,  0.        ]), array([0.01703813, 0.        ]))

In [ ]:
''' Now to plot the lines made at each layer '''

# layer 1 lines
def linear(slope, intercept):
    x = np.linspace(-10,10,101)
    return x*slope + intercept

y11 = linear(0, W1[1])
y12 = None

y21 = None
y22 = linear(a11[0], 0)

