In [1]:
import numpy as np

In [4]:
Z = np.random.rand(3,2,4)
Z

array([[[0.90655948, 0.87516048, 0.72854381, 0.76470628],
        [0.4279056 , 0.39783869, 0.63368914, 0.55482699]],

       [[0.73828853, 0.12093726, 0.75332192, 0.58525391],
        [0.67051837, 0.82508448, 0.44141859, 0.84745429]],

       [[0.28732762, 0.597262  , 0.78948747, 0.59848052],
        [0.66640044, 0.74825536, 0.51515373, 0.60001835]]])

In [25]:
Z.shape

(3, 2, 4)

In [8]:
for i, A in enumerate(Z.transpose(0,2,1)):
    print('This is the first object: {}'.format(i))
    print('This is the second object: \n{}'.format(A))

This is the first object: 0
This is the second object: 
[[0.90655948 0.4279056 ]
 [0.87516048 0.39783869]
 [0.72854381 0.63368914]
 [0.76470628 0.55482699]]
This is the first object: 1
This is the second object: 
[[0.73828853 0.67051837]
 [0.12093726 0.82508448]
 [0.75332192 0.44141859]
 [0.58525391 0.84745429]]
This is the first object: 2
This is the second object: 
[[0.28732762 0.66640044]
 [0.597262   0.74825536]
 [0.78948747 0.51515373]
 [0.59848052 0.60001835]]


In [10]:
X = np.random.rand(3,4)
X

array([[0.22061529, 0.88017188, 0.27979979, 0.18932592],
       [0.28154013, 0.5279832 , 0.80689523, 0.03586219],
       [0.91718388, 0.87098857, 0.76102898, 0.53948432]])

In [16]:
for i, A in enumerate(Z.transpose(0,2,1)):
    print('A.T is :\n {}'.format(A.T))
    print('X[i] is: \n{}'.format(X[i]))
    print(A.T - X[i])

A.T is :
 [[0.90655948 0.87516048 0.72854381 0.76470628]
 [0.4279056  0.39783869 0.63368914 0.55482699]]
X[i] is: 
[0.22061529 0.88017188 0.27979979 0.18932592]
[[ 0.6859442  -0.00501141  0.44874403  0.57538036]
 [ 0.20729031 -0.48233319  0.35388935  0.36550107]]
A.T is :
 [[0.73828853 0.12093726 0.75332192 0.58525391]
 [0.67051837 0.82508448 0.44141859 0.84745429]]
X[i] is: 
[0.28154013 0.5279832  0.80689523 0.03586219]
[[ 0.4567484  -0.40704594 -0.05357331  0.54939172]
 [ 0.38897824  0.29710128 -0.36547664  0.8115921 ]]
A.T is :
 [[0.28732762 0.597262   0.78948747 0.59848052]
 [0.66640044 0.74825536 0.51515373 0.60001835]]
X[i] is: 
[0.91718388 0.87098857 0.76102898 0.53948432]
[[-0.62985626 -0.27372657  0.02845849  0.05899621]
 [-0.25078344 -0.12273321 -0.24587525  0.06053404]]


In [13]:
for i in range(X.shape[0]):
    print(X[i])

[0.22061529 0.88017188 0.27979979 0.18932592]
[0.28154013 0.5279832  0.80689523 0.03586219]
[0.91718388 0.87098857 0.76102898 0.53948432]


In [17]:
np.dot(X,X.T)

array([[0.93750588, 0.75938678, 1.28403855],
       [0.75938678, 1.0103971 , 1.35150914],
       [1.28403855, 1.35150914, 2.4700558 ]])

In [26]:
G = np.dot(X,X.T)
G.flat[::Z.shape[1]+1] += 1/1000
G

array([[0.93850588, 0.75938678, 1.28403855],
       [0.76038678, 1.0103971 , 1.35150914],
       [1.28503855, 1.35150914, 2.4700558 ]])

In [23]:
Z.shape[1]+1

3